name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 bandit

      - name: Lint code with flake8
        run: flake8 .

      - name: Run tests with pytest
        run: pytest --junitxml=pytest-report.xml --cov=app --cov-report=xml

      - name: Run security scan with Bandit
        run: bandit -r app

